version: '3'
services:
    #Neo4j Service
    neo4j:
        image: neo4j:4.4.9-community
        restart: unless-stopped
        tty: true
        ports:
            - "7687:7687"
            - "7474:7474"
        environment:
            NEO4J_AUTH: "neo4j/--PASSWORD--"
        volumes:
            - ./neo4j/data:/data
        networks:
            - neo4j-ntwrk
#Docker Networks
networks:
    neo4j-ntwrk:
        driver: bridge
